#!/usr/bin/env python

import os
import datetime

filenames = os.listdir(os.curdir)
count = 0
for filename in filenames:
    if filename.endswith(".log"):
        count = count + 1
        print (filename + " found.")
if count == 0:
    print("No log file found")
    scriptName = os.path.basename(__file__)
    newLog = scriptName.replace(".py",".log")
    print("Creating " + newLog)
    log = open(newLog, 'w+')
    curDate = datetime.datetime.today()
    dateStamp = curDate.strftime("%d-%m-%Y  %H:%M:%S")
    print (dateStamp)
    log.write(dateStamp + "   :Log file automatically generated by logChk.py")
    log.close()
